[connections]
host = "violet-opossum-12877.7tt.cockroachlabs.cloud"
port = '26257'
dbname = 'streamlit_tkt_app'
user = "stkt_user"
password = "AQFKR75HQWNJ0nmHLX9ciA"
sslmode = "verify-full"
# sslrootcert=temp_cert_file_path
# sslcert = /path/to/client.crt
# sslkey = /path/to/client.key


[CA_CERT]
bucket = 'dtc-prefect-etl-bucket'
Access_key_ID = 'AKIAY5IXX7AGLXJPTDMN'
Secret_access_key = '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'
file='postgresql/root.crt'

